#!/bin/bash
mkdir -p ./secret/app-example-org/dev
uuidgen > ./secret/app-example-org/dev/jump.pat
uuidgen > ./secret/app-example-org/dev/book.pat
cp ./secret/app-example-org/dev/book.pat ./secret/app-example-org/dev/relay.pat
echo "some-project-0000" > ./secret/app-example-org/dev/project

mkdir -p ./secret/app-example-org/xx0
uuidgen > ./secret/app-example-org/xx0/jump.pat
uuidgen > ./secret/app-example-org/xx0/book.pat
cp ./secret/app-example-org/xx0/book.pat ./secret/app-example-org/xx0/relay.pat
echo "some-project-0000" > ./secret/app-example-org/xx0/project



